// <auto-generated />
namespace RestApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SumRefDateColumnadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SumRefDateColumnadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201809091436474_SumRefDate-Column-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
