// <auto-generated />
namespace RestApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sumchartostring215489 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sumchartostring215489));
        
        string IMigrationMetadata.Id
        {
            get { return "201809081624013_sumchartostring215489"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
